### ISSUE TITLE
Failed to deploy claim-review

### ISSUE THREAD

**Issue by peteryxu** [aws-solutions-library-samples/guidance-for-multimodal-data-processing-using-amazon-bedrock-data-automation#53]
i was able to deploy lending app, but  deployment of claims-review failed immediately.  It is related to database and aurorav2 as seen below.  Has anyone else encountered this error?

##############

(.venv) peter@wsstl1840 deployment % cdk deploy claims-review  --context foundation_model_id=anthropic.claude-3-5-sonnet-20241022-v2:0 --require-approval never 
Preparing stacks with configuration:
{
  "deploy_claims_review": true,
  "deploy_lending_flow": true
}
Traceback (most recent call last):
  File "/Users/peter/CODE/aws/aws-guidance-for-multimodal-data-processing-using-amazon-bedrock-data-automation/deployment/app.py", line 43, in <module>
    ClaimsReviewAgentStack(app, "claims-review",
  File "/Users/peter/CODE/aws/aws-guidance-for-multimodal-data-processing-using-amazon-bedrock-data-automation/.venv/lib/python3.11/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  **File "/Users/peter/CODE/aws/aws-guidance-for-multimodal-data-processing-using-amazon-bedrock-data-automation/deployment/stacks/claims_review_stack/agent.py", line 44, in __init__
    aurora_serverless_v2 = Database(self,"auroraV2")**
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peter/CODE/aws/aws-guidance-for-multimodal-data-processing-using-amazon-bedrock-data-automation/.venv/lib/python3.11/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peter/CODE/aws/aws-guidance-for-multimodal-data-processing-using-amazon-bedrock-data-automation/deployment/stacks/claims_review_stack/database.py", line 27, in __init__
    manage_schema_lambda_function = self.create_manage_schema_lambda_function(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peter/CODE/aws/aws-guidance-for-multimodal-data-processing-using-amazon-bedrock-data-automation/deployment/stacks/claims_review_stack/database.py", line 136, in create_manage_schema_lambda_function
    manage_schema_lambda_function = _lambda.Function(
                                    ^^^^^^^^^^^^^^^^^
  File "/Users/peter/CODE/aws/aws-guidance-for-multimodal-data-processing-using-amazon-bedrock-data-automation/.venv/lib/python3.11/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Function.__init__() got an unexpected keyword argument 'Duration'
Subprocess exited with error 1

**Comment by rajavaid77** [comment]
thanks. I will have a look and apply a fix

**Comment by ArlindNocaj** [comment]
@peteryxu can you please confirm that the fix resolved your issue?
